// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDGGIH_K-FksGI7mTKVhrJg5houN93hcA',
    appId: '1:577531165921:web:b5e4770b4e18b3054a8ba0',
    messagingSenderId: '577531165921',
    projectId: 'craftybay-c6d41',
    authDomain: 'craftybay-c6d41.firebaseapp.com',
    storageBucket: 'craftybay-c6d41.firebasestorage.app',
    measurementId: 'G-D96QMS2W0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Vs0Vvd5yMmXRuHpeP36nb5zVKBpOwpw',
    appId: '1:577531165921:android:875f471e83f353ff4a8ba0',
    messagingSenderId: '577531165921',
    projectId: 'craftybay-c6d41',
    storageBucket: 'craftybay-c6d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjoGeztKGkITFQUCuZTCQ2kV7D8KI63Mc',
    appId: '1:577531165921:ios:2f78ae1e5f85ae4d4a8ba0',
    messagingSenderId: '577531165921',
    projectId: 'craftybay-c6d41',
    storageBucket: 'craftybay-c6d41.firebasestorage.app',
    iosBundleId: 'y',
  );
}
